export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
        <html lang="en">
          <body className="bg-gray-50 dark:bg-gray-800">{children}</body>
        </html>
    )
}
